'use strict';
const SS = window.SmartSantri;
const app = document.getElementById('app');
const dialog = document.getElementById('dialog');
const h = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const initials = name => name.split(' ').slice(0,2).map(s => s[0]).join('').toUpperCase();
const fmtDate = value => new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeZone:'Asia/Jakarta'}).format(new Date(value));
const fmtTime = value => new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:'Asia/Jakarta'}).format(new Date(value));
const fmtFull = value => `${fmtDate(value)} · ${fmtTime(value)} WIB`;
const iconPaths = {
  book:'M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4V4Zm16 0h-4a3 3 0 0 0-3 3v14a4 4 0 0 1 4-2h5V4h-2Z',
  grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',
  check:'m5 12 4 4L19 6', clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',
  users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.87M15 3.13a4 4 0 0 1 0 7.75M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
  star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z',
  news:'M4 3h16v18H4V3Zm4 4h8M8 11h8M8 15h4M8 18h8',
  settings:'M4 7h16M4 17h16M8 3v8M16 13v8', logout:'M9 4H4v16h5M10 12h11m-4-4 4 4-4 4',
  plus:'M12 5v14M5 12h14', arrow:'M4 12h16m-6-6 6 6-6 6', download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',
  file:'M14 2H6v20h14V8l-6-6Zm0 0v6h6M9 13h6M9 17h6', edit:'m16 3 5 5-12 12-6 1 1-6L16 3Z',
  trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7', chevron:'m9 5 7 7-7 7', back:'M20 12H4m6-6-6 6 6 6',
  lock:'M5 11h14v10H5V11Zm3 0V7a4 4 0 0 1 8 0v4', menu:'M4 6h16M4 12h16M4 18h16', close:'m6 6 12 12M6 18 18 6'
};
const ico = (name, size=20) => `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPaths[name] || iconPaths.book}"/></svg>`;
const brand = `<a class="brand" href="./index.html"><span class="brand-mark">${ico('book',24)}</span><span>smart<span class="light">santri</span><b>.</b></span></a>`;
const btn = (label, action, data='', style='primary', icon='plus') => `<button type="button" class="btn ${style}" data-action="${action}" ${data}>${icon ? ico(icon,18) : ''}${label}</button>`;
const linkBtn = (label, route, style='primary', icon='arrow') => `<a class="btn ${style}" href="#/${route}">${label}${icon ? ico(icon,18) : ''}</a>`;
const empty = (title, desc, action='') => `<div class="empty-state"><span>${ico('book',28)}</span><h3>${title}</h3><p>${desc}</p>${action}</div>`;
const pill = (label, cls='') => `<span class="pill ${cls}">${h(label)}</span>`;
let model, filter = '', builder = [], pendingSubmission, toastTimer, loginRedirect = 'dashboard';
let objectUrls = [];
const session = { get(k) { try{return sessionStorage.getItem(k)}catch{return null} }, set(k,v) { try{sessionStorage.setItem(k,v)}catch{} }, remove(k) { try{sessionStorage.removeItem(k)}catch{} } };
const current = () => { const [path, search=''] = (location.hash.slice(2) || 'dashboard').split('?'); return { parts: path.split('/'), query: new URLSearchParams(search) }; };
const className = id => model.find('classes',id)?.name || '—';
const subjectName = id => model.find('subjects',id)?.name || '—';
const userName = id => model.find('users',id)?.name || 'Akun tidak tersedia';
const author = item => `${userName(item.authorId)} · ${fmtDate(item.createdAt)}`;
function toast(message, error=false) { const box=document.getElementById('toast'); clearTimeout(toastTimer); box.textContent=message; box.className=`show ${error?'error':''}`; toastTimer=setTimeout(()=>box.className='',5000); }
function pageHead(eyebrow,title,description='',action='') { return `<div class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${description?`<p class="page-description">${description}</p>`:''}</div>${action}</div>`; }
function modal(title,body,cls='') { dialog.className=cls; dialog.innerHTML=`<div class="modal-head"><h2 id="dialog-title">${title}</h2><button class="icon-btn" type="button" data-action="close-dialog" aria-label="Tutup">${ico('close')}</button></div>${body}`; if (!dialog.open) dialog.showModal(); }
function closeModal(){dialog.close(); dialog.innerHTML='';}
function showError(form,err) { const box=form?.querySelector('.form-error'); if(box){box.textContent=err.message||String(err); box.hidden=false;box.focus();}else toast(err.message||String(err),true); }
const errorBox = '<p class="form-error" role="alert" tabindex="-1" hidden></p>';
function field(label,name,value='',type='text',attrs='') { return `<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${h(value)}" ${attrs}></label>`; }
function area(label,name,value='',attrs=''){return `<label class="field"><span>${label}</span><textarea name="${name}" rows="4" ${attrs}>${h(value)}</textarea></label>`;}
function select(label,name,items,value='',required=true){return `<label class="field"><span>${label}</span><select name="${name}" ${required?'required':''}><option value="">Pilih ${label.toLowerCase()}</option>${items.map(x=>`<option value="${h(x.id)}" ${x.id===value?'selected':''}>${h(x.name)}</option>`).join('')}</select></label>`;}
function checks(label,name,items,values=[]){return `<fieldset class="check-group"><legend>${label}</legend>${items.length?items.map(item=>`<label><input type="checkbox" name="${name}" value="${h(item.id)}" ${values.includes(item.id)?'checked':''}>${h(item.name)}</label>`).join(''):'<p class="muted">Belum ada data. Buat melalui Data sekolah.</p>'}</fieldset>`;}
function formFooter(label='Simpan'){return `${errorBox}<div class="form-actions"><button type="button" class="btn secondary" data-action="close-dialog">Batal</button><button class="btn primary" type="submit">${label}${ico('check',18)}</button></div>`;}
function publicShell(content,active){return `<header class="public-header">${brand}<nav aria-label="Navigasi portal"><a href="./index.html">Beranda</a><a href="#/attendance" ${active==='attendance'?'aria-current="page"':''}>Absensi</a><a href="#/news" ${active==='news'?'aria-current="page"':''}>Kabar sekolah</a>${linkBtn(model.actor?'Buka dashboard':'Masuk',model.actor?'dashboard':'login','primary','')}</nav></header><main id="main-content" tabindex="-1" class="public-main">${content}</main><footer class="public-footer">Smart Santri · SD & MI <span>Trial dengan data contoh</span></footer>`;}
function shell(content,active){
  const u=model.actor;
  const items=[['dashboard','grid','Ringkasan'],['learn','book','Ruang belajar'],['clubs','star','Ekstrakurikuler'],['history','clock','Kehadiran'],['news','news','Kabar sekolah']];
  if(u.role==='admin')items.push(['admin','settings','Data sekolah'],['publications','edit','Publikasi']);
  return `<div class="workspace"><aside class="sidebar" id="sidebar">${brand}<div class="school-label">PORTAL SD / MI</div><nav aria-label="Navigasi aplikasi">${items.map(([route,icon,label])=>`<a class="side-link ${active===route?'active':''}" href="#/${route}" ${active===route?'aria-current="page"':''}>${ico(icon)}${label}</a>`).join('')}</nav><a class="kiosk-link" href="#/attendance">${ico('check')}Buka mesin absensi${ico('arrow',17)}</a><div class="sidebar-bottom"><div class="avatar">${h(initials(u.name))}</div><div><strong>${h(u.name)}</strong><small>${SS.roles[u.role]} · ${h(u.code)}</small></div><button class="icon-btn" type="button" data-action="logout" aria-label="Keluar">${ico('logout')}</button></div></aside><div class="main-column"><header class="workspace-header"><button class="icon-btn mobile-menu" type="button" data-action="toggle-sidebar" aria-controls="sidebar" aria-expanded="false" aria-label="Buka navigasi">${ico('menu')}</button><div class="breadcrumb">Smart Santri <span>/</span> ${h(items.find(i=>i[0]===active)?.[2] || 'Portal')}</div><span class="date-chip">${fmtDate(new Date())}</span></header><main id="main-content" tabindex="-1" class="workspace-main">${content}</main><footer class="app-footer"><span>Smart Santri · Cerdas ilmunya. Baik akhlaknya.</span><span>SD & Madrasah Ibtidaiyah</span></footer></div></div>`;
}
function dashboard(){
  const u=model.actor, materials=model.visible('materials'),tasks=model.visible('assignments');
  const mine=model.data.submissions.filter(s=>s.studentId===u.id),todo=tasks.filter(t=>!mine.some(s=>s.assignmentId===t.id));
  const cards=u.role==='admin'?[['users','Siswa terdaftar',model.data.users.filter(u=>u.role==='siswa').length],['book','Kelas aktif',model.data.classes.length],['check','Hadir hari ini',model.data.attendance.filter(a=>a.day===SS.jakartaDay()).length],['star','Ekstrakurikuler',model.data.clubs.length]]:[['book','Materi tersedia',materials.length],['file',u.role==='siswa'?'Tugas belum dikerjakan':'Tugas kelas',u.role==='siswa'?todo.length:tasks.length],['check','Kehadiran saya',model.data.attendance.filter(a=>a.userId===u.id).length],['star',u.role==='siswa'?'Rata-rata nilai':'Kelas / eskul dibina',u.role==='siswa'?(mine.length?Math.round(mine.reduce((sum,s)=>sum+s.score,0)/mine.length):'—'):(u.classIds.length+model.data.clubs.filter(c=>c.coachIds.includes(u.id)).length)]];
  return pageHead('SELAMAT DATANG',`Assalamu’alaikum, ${h(u.name)}.`,u.role==='siswa'?`Mari belajar hal baru hari ini. Kamu berada di kelas <strong>${h(className(u.classId))}</strong>.`:'Semua kegiatan sekolah, dalam satu ruang yang terhubung.',linkBtn('Catat kehadiran','attendance','secondary','check'))+`<div class="stats-grid">${cards.map(([i,l,v])=>`<article class="stat"><span>${ico(i)}</span><p>${l}</p><strong>${v}</strong></article>`).join('')}</div><div class="dashboard-grid"><section class="panel"><div class="panel-title"><h2>${u.role==='siswa'?'Lanjutkan belajarmu':'Ruang belajar'}</h2><a href="#/learn">Lihat semua ${ico('arrow',17)}</a></div>${materials.length?materials.slice(0,3).map(m=>`<a class="list-row" href="#/material/${m.id}"><span class="row-icon">${ico('book')}</span><div><strong>${h(m.title)}</strong><small>${h(m.clubId?model.find('clubs',m.clubId)?.name:subjectName(m.subjectId))} · ${h(userName(m.authorId))}</small></div>${ico('chevron',18)}</a>`).join(''):empty('Materi belum tersedia','Materi yang sesuai dengan akun Anda akan muncul di sini.')}</section><section class="panel announcement-panel"><div class="panel-title"><h2>Papan informasi</h2>${ico('news')}</div>${model.data.announcements.slice(0,3).map(a=>`<article class="announcement"><small>${fmtDate(a.createdAt)}</small><h3>${h(a.title)}</h3><p>${h(a.content)}</p></article>`).join('')||'<p class="muted">Belum ada informasi sekolah.</p>'}</section></div><section class="welcome-strip"><div><p class="eyebrow">SEKOLAH DAN KELUARGA, BERJALAN BERSAMA</p><h2>Langkah kecil hari ini.<br>Masa depan berarti.</h2><a href="#/news">Jelajahi kabar sekolah ${ico('arrow',18)}</a></div><img src="./assets/belajar-bersama.webp" alt="Ilustrasi anak-anak belajar bersama" width="1448" height="1086"></section>`;
}
function login(){
  if(model.actor){location.hash='/dashboard';return '';}
  return publicShell(`<section class="login-layout"><div class="login-story"><p class="eyebrow">RUANG DIGITAL SEKOLAH KITA</p><h1>Belajar, berkarya,<br><span>tumbuh bersama.</span></h1><p>Masuk ke Smart Santri menggunakan ID yang diberikan oleh admin sekolah.</p><img src="./assets/belajar-bersama.webp" alt="Ilustrasi siswa madrasah belajar" width="1448" height="1086"></div><div class="login-box"><span class="large-icon">${ico('book',28)}</span><h2>Selamat datang kembali</h2><p>Masukkan ID akun Anda untuk melanjutkan.</p><form data-form="login">${field('ID pengguna','code','','text','required autocomplete="username" placeholder="Contoh: SISWA001" maxlength="30" autocapitalize="characters"')}${errorBox}<button type="submit" class="btn primary full">Masuk ke portal ${ico('arrow',18)}</button></form><div class="demo-accounts"><div><strong>Coba dengan akun demo</strong><span>Pilih peran untuk mengisi ID</span></div>${[['ADMIN001','Admin sekolah'],['GURU001','Guru kelas IV A'],['ESKUL001','Pembina tahfidz'],['SISWA001','Siswa kelas IV A']].map(([id,name])=>`<button type="button" data-action="demo-id" data-code="${id}"><span>${name}</span><code>${id}</code></button>`).join('')}</div><p class="login-note">Login ID saja digunakan untuk trial. Siapa pun yang mengetahui ID demo dapat mencoba peran tersebut. Jangan masukkan data siswa sungguhan.</p></div></section>`,'login');
}
function attendance(){
  return publicShell(`<div class="attendance-layout"><section class="attendance-intro"><p class="eyebrow">ABSENSI SISWA & GURU</p><h1>Selamat datang.<br><span>Sudah siap belajar?</span></h1><p>Masukkan ID, lalu periksa identitas dan waktu kehadiran Anda.</p><div class="clock-panel"><span id="live-date">${fmtDate(new Date())}</span><strong id="live-clock">${fmtTime(new Date())}</strong><small>WAKTU INDONESIA BARAT</small></div><p class="attendance-note">Satu catatan hadir per orang per hari. Waktu mengikuti perangkat dan ditampilkan dalam WIB.</p></section><section class="attendance-card"><span class="large-icon">${ico('check',30)}</span><h2>Catat kehadiran</h2><p>Gunakan ID siswa atau guru dari sekolah.</p><form data-form="attendance">${field('ID siswa / guru','code','','text','required placeholder="Contoh: SISWA001" maxlength="30" autocomplete="off" autocapitalize="characters"')}${errorBox}<button type="submit" class="btn primary full">Saya hadir ${ico('check',18)}</button></form><div class="hint-box"><strong>ID untuk mencoba</strong><p><code>SISWA001</code> Alya Rahma<br><code>GURU001</code> Ibu Salma</p></div><a class="text-link" href="#/${model.actor?'history':'login'}">${model.actor?'Lihat riwayat kehadiran':'Masuk ke portal belajar'} ${ico('arrow',17)}</a></section></div>`,'attendance');
}
function attendancePopup(result){const {record:r,user:u,duplicate}=result;modal(duplicate?'Kehadiran sudah tercatat':'Alhamdulillah, hadir!',`<div class="attendance-success"><span class="success-seal">${ico('check',40)}</span><p>${duplicate?'Anda sudah melakukan absensi hari ini. Berikut catatan pertamanya.':'Kehadiran berhasil disimpan pada browser ini.'}</p><div class="profile-result"><span class="avatar large">${h(initials(u.name))}</span><h3>${h(u.name)}</h3><p>${SS.roles[u.role]}${u.classId?' · Kelas '+h(className(u.classId)):''}</p><code>${h(u.code)}</code></div><div class="result-time"><span>${fmtDate(r.time)}</span><strong>${fmtTime(r.time)} <small>WIB</small></strong>${pill('Hadir','green')}</div><button class="btn primary full" data-action="close-dialog" type="button">Selesai</button></div>`,'narrow');}
function accessibleClasses(){const u=model.actor;return model.data.classes.filter(c=>u.role==='admin'||u.classId===c.id||u.classIds.includes(c.id));}
function accessibleClubs(){const u=model.actor;return model.data.clubs.filter(c=>u.role==='admin'||c.coachIds.includes(u.id)||(u.role==='siswa'&&u.clubIds.includes(c.id)));}
function materialCard(m){return `<article class="resource-card"><div class="resource-top"><span class="resource-icon">${ico('book',24)}</span>${pill(m.downloadable?'Dapat diunduh':'Baca di portal',m.downloadable?'green':'')}</div><small>${h(m.clubId?model.find('clubs',m.clubId)?.name:subjectName(m.subjectId))}</small><h3><a href="#/material/${m.id}">${h(m.title)}</a></h3><p>${h(m.content.slice(0,135))}${m.content.length>135?'…':''}</p><div class="resource-bottom"><span>${h(userName(m.authorId))}</span><a href="#/material/${m.id}" aria-label="Buka ${h(m.title)}">${ico('arrow',18)}</a></div></article>`;}
function taskCard(t){const mine=model.data.submissions.find(s=>s.studentId===model.actor.id&&s.assignmentId===t.id);const late=t.dueAt&&new Date(t.dueAt)<new Date();return `<article class="task-row"><span class="row-icon">${ico('file',22)}</span><div><small>${h(subjectName(t.subjectId))}</small><h3>${h(t.title)}</h3><p>${t.questions.length} soal · ${t.dueAt?'Batas: '+fmtFull(t.dueAt):'Tanpa batas waktu'}${mine?' · Nilai '+mine.score:''}</p></div>${model.actor.role==='siswa'?linkBtn(mine?'Lihat nilai':late?'Waktu habis':'Kerjakan',`task/${t.id}`,mine?'secondary':'primary',''):linkBtn('Lihat tugas',`task/${t.id}`,'secondary','')}</article>`;}
function learning(id){
  const classes=accessibleClasses();
  if(!id)return pageHead('RUANG BELAJAR','Satu kelas. Banyak cerita.','Pilih kelas untuk membaca materi dan mengerjakan tugas.')+`<div class="class-grid">${classes.map(c=>{const materials=model.visible('materials').filter(m=>m.classId===c.id),tasks=model.visible('assignments').filter(t=>t.classId===c.id);return `<a class="class-card" href="#/learn/${c.id}"><div class="class-visual"><span>${ico('book',44)}</span><b>${h(c.level)}</b></div><div><small>TAHUN AJARAN ${h(c.year)}</small><h2>Kelas ${h(c.name)}</h2><p>${materials.length} materi · ${tasks.length} tugas</p><span class="class-open">Masuk ruang kelas ${ico('arrow',18)}</span></div></a>`;}).join('')||empty('Belum ada kelas','Admin sekolah perlu menempatkan akun Anda pada kelas atau penugasan mengajar.')}</div>`;
  const c=classes.find(c=>c.id===id);if(!c)return accessDenied();
  const materials=model.visible('materials').filter(m=>m.classId===id),tasks=model.visible('assignments').filter(t=>t.classId===id);
  return `<a class="back-link" href="#/learn">${ico('back',16)}Semua kelas</a>`+pageHead(`RUANG BELAJAR · ${h(c.year)}`,`Kelas ${h(c.name)}`,'Materi dan tugas dari guru kelas Anda.',['admin','guru'].includes(model.actor.role)?`<div class="actions">${btn('Tambah materi','edit-material',`data-class="${id}"`,'secondary','plus')}${btn('Buat tugas','edit-task',`data-class="${id}"`)}</div>`:'')+`<div class="section-heading"><h2>Materi pembelajaran</h2><span>${materials.length} materi</span></div><div class="resource-grid">${materials.map(materialCard).join('')||empty('Materi belum tersedia','Materi yang diunggah guru akan muncul di sini.')}</div><div class="section-heading space-top"><h2>Tugas kelas</h2><span>${tasks.length} tugas</span></div><div class="panel task-list">${tasks.map(taskCard).join('')||empty('Belum ada tugas','Selamat belajar! Tugas baru akan muncul di sini.')}</div>`;
}
function clubs(id){const list=accessibleClubs();
  if(!id)return pageHead('EKSTRAKURIKULER','Temukan minat. Tumbuhkan bakat.','Ruang kegiatan dan materi bersama pembina ekstrakurikuler.')+`<div class="club-grid">${list.map((c,i)=>`<article class="club-card"><div class="club-mark ${i%2?'ochre':''}">${ico('star',35)}</div><h2>${h(c.name)}</h2><p>${h(c.description)}</p><div class="club-details"><span>${ico('clock',16)}${h(c.schedule||'Jadwal belum ditetapkan')}</span><span>${ico('users',16)}${h(c.coachIds.map(userName).join(', '))}</span></div>${linkBtn('Buka kegiatan',`clubs/${c.id}`,'secondary')}</article>`).join('')||empty('Belum mengikuti eskul','Admin dapat menambahkan keanggotaan atau penugasan pembina pada Data sekolah.')}</div>`;
  const c=list.find(c=>c.id===id);if(!c)return accessDenied();const materials=model.visible('materials').filter(m=>m.clubId===id);
  return `<a class="back-link" href="#/clubs">${ico('back',16)}Semua ekstrakurikuler</a>`+pageHead('EKSTRAKURIKULER',h(c.name),h(c.description),model.coach(id)?btn('Unggah materi','edit-material',`data-club="${id}"`):'')+`<div class="info-strip"><span>${ico('clock',18)}${h(c.schedule||'Jadwal belum ditetapkan')}</span><span>${ico('users',18)}Pembina: ${h(c.coachIds.map(userName).join(', '))}</span></div><div class="section-heading"><h2>Materi kegiatan</h2><span>${materials.length} materi</span></div><div class="resource-grid">${materials.map(materialCard).join('')||empty('Materi belum tersedia','Pembina belum mengunggah materi untuk kegiatan ini.')}</div>`;
}
function material(id){const m=model.find('materials',id);if(!m||!model.canRead(m))return accessDenied();return `<a class="back-link" href="#/${m.clubId?'clubs/'+m.clubId:'learn/'+m.classId}">${ico('back',16)}Kembali ke ${m.clubId?'kegiatan':'kelas'}</a>`+pageHead(h(m.clubId?model.find('clubs',m.clubId)?.name:subjectName(m.subjectId)),h(m.title),h(author(m)),model.canEdit(m)?`<div class="actions">${btn('Edit','edit-material',`data-id="${id}"`,'secondary','edit')}${btn('Hapus','delete-material',`data-id="${id}"`,'danger-quiet','trash')}</div>`:'')+`<article class="reading-panel"><div class="prose">${h(m.content).replace(/\n/g,'<br>')}</div>${m.fileId?`<div class="attachment"><span class="row-icon">${ico('file',25)}</span><div><strong>${h(m.fileName||'Lampiran materi')}</strong><p>${m.downloadable?'Bisa dibaca dan diunduh':'Baca di portal · Unduh dinonaktifkan'}</p></div>${btn('Buka lampiran','view-file',`data-id="${id}"`,'secondary','book')}</div>`:''}<div class="reading-footer">${pill(m.downloadable?'Unduh diizinkan':'Baca di portal',m.downloadable?'green':'')}${m.downloadable?btn(m.fileId?'Unduh lampiran':'Unduh materi','download-material',`data-id="${id}"`,'primary','download'):''}</div></article>`;}
function task(id){const t=model.find('assignments',id);if(!t||!model.canRead(t))return accessDenied();const u=model.actor,mine=model.data.submissions.find(s=>s.assignmentId===id&&s.studentId===u.id);const back=`<a class="back-link" href="#/learn/${t.classId}">${ico('back',16)}Kembali ke kelas ${h(className(t.classId))}</a>`;
  if(u.role==='siswa'&&mine)return back+resultView(t,mine);
  if(u.role!=='siswa')return back+pageHead(h(subjectName(t.subjectId)),h(t.title),h(t.description),model.canEdit(t)?`<div class="actions">${btn('Edit tugas','edit-task',`data-id="${id}"`,'secondary','edit')}${btn('Hapus','delete-task',`data-id="${id}"`,'danger-quiet','trash')}</div>`:'')+`<div class="info-strip"><span>${t.questions.length} soal · ${t.questions.reduce((a,q)=>a+q.points,0)} bobot total</span><span>${t.dueAt?'Batas: '+fmtFull(t.dueAt):'Tanpa batas waktu'}</span></div><div class="tabs"><a class="active" href="#/task/${id}">Pratinjau & kunci jawaban</a><a href="#/results/${id}">Hasil siswa (${model.data.submissions.filter(s=>s.assignmentId===id).length})</a></div><div class="question-stack">${t.questions.map((q,i)=>`<article class="question-card"><div class="question-number">PERTANYAAN ${i+1}<span>${q.points} poin</span></div><h3>${h(q.text)}</h3>${q.options.map((v,j)=>`<div class="answer-preview ${String(j)===q.answer?'correct':''}">${String(j)===q.answer?ico('check',17):'<span class="radio-dot"></span>'}${h(v)}</div>`).join('')}${q.type==='short'?`<div class="answer-preview correct">${ico('check',17)}${h(q.answer.split('|').join(' / '))}</div>`:''}</article>`).join('')}</div>`;
  const late=t.dueAt&&Date.now()>new Date(t.dueAt).getTime(); let draft={};try{draft=JSON.parse(session.get('draft-'+u.id+'-'+id)||'{}')}catch{}
  return back+pageHead(h(subjectName(t.subjectId)),h(t.title),h(t.description))+`<div class="info-strip"><span>${t.questions.length} soal · Semua pertanyaan wajib dijawab</span><span>${t.dueAt?'Batas: '+fmtFull(t.dueAt):'Tanpa batas waktu'}</span></div>${late?'<div class="notice danger">Batas waktu pengumpulan telah lewat. Tugas tidak dapat dikirim.</div>':''}<form data-form="take-task" data-id="${id}" class="question-stack"><div class="form-progress"><span id="answered-count">0 dari ${t.questions.length} soal terjawab</span><span>Satu kali pengumpulan</span></div>${t.questions.map((q,i)=>`<fieldset class="question-card"><legend><span class="question-number">PERTANYAAN ${i+1}<span>${q.points} poin</span></span><span class="question-text">${h(q.text)} <span class="required" aria-label="wajib">*</span></span></legend>${q.type==='short'?`<input class="short-answer" name="${q.id}" aria-label="Jawaban pertanyaan ${i+1}" value="${h(draft[q.id]||'')}" placeholder="Tulis jawaban singkat…" required maxlength="500" ${late?'disabled':''}>`:q.options.map((v,j)=>`<label class="answer-option"><input type="radio" name="${q.id}" value="${j}" ${draft[q.id]===String(j)?'checked':''} required ${late?'disabled':''}>${h(v)}</label>`).join('')}</fieldset>`).join('')}${errorBox}<div class="task-submit"><p>Periksa kembali jawabanmu. Nilai muncul setelah dikirim.</p><button class="btn primary" type="submit" ${late?'disabled':''}>Kirim jawaban ${ico('arrow',18)}</button></div></form>`;
}
function resultView(t,s){return pageHead('HASIL BELAJAR',h(t.title),'Jawaban berhasil dikumpulkan. Terima kasih sudah berusaha!')+`<section class="score-panel"><span class="success-seal">${ico('check',34)}</span><div><small>NILAI KAMU</small><strong>${s.score}<span>/ 100</span></strong></div><div class="score-details"><span>${s.answers.filter(a=>a.correct).length} dari ${s.answers.length} jawaban benar</span><span>Bobot diperoleh: ${s.earned} / ${s.possible}</span><span>${fmtFull(s.submittedAt)}</span></div></section><div class="section-heading"><h2>Tinjau jawabanmu</h2></div><div class="question-stack">${t.questions.map((q,i)=>{const a=s.answers.find(a=>a.questionId===q.id);return `<article class="question-card"><div class="question-number">PERTANYAAN ${i+1}${pill(a.correct?'Benar':'Belum tepat',a.correct?'green':'red')}</div><h3>${h(q.text)}</h3><p class="review-answer">Jawabanmu: <strong>${h(q.type==='short'?a.value:q.options[Number(a.value)])}</strong></p>${!a.correct?`<p class="review-correct">Jawaban benar: ${h(q.type==='short'?q.answer.split('|').join(' / '):q.options[Number(q.answer)])}</p>`:''}<small>${a.earned} / ${a.possible} poin</small></article>`;}).join('')}</div>`;}
function results(id){const t=model.find('assignments',id);if(!t||!model.canRead(t)||model.actor.role==='siswa')return accessDenied();const students=model.data.users.filter(u=>u.role==='siswa'&&u.classId===t.classId),submitted=model.data.submissions.filter(s=>s.assignmentId===id);return `<a class="back-link" href="#/task/${id}">${ico('back',16)}Kembali ke tugas</a>`+pageHead('HASIL & NILAI SISWA',h(t.title),`${submitted.length} dari ${students.length} siswa sudah mengumpulkan.`,btn('Ekspor nilai','export-scores',`data-id="${id}"`,'secondary','download'))+`<div class="table-wrap"><table><thead><tr><th>Siswa</th><th>ID</th><th>Status</th><th>Nilai</th><th>Dikumpulkan</th><th>Rincian</th></tr></thead><tbody>${students.map(u=>{const s=submitted.find(s=>s.studentId===u.id);return `<tr><td><strong>${h(u.name)}</strong></td><td><code>${h(u.code)}</code></td><td>${pill(s?'Dikumpulkan':'Belum mengumpulkan',s?'green':'')}</td><td><strong>${s?s.score:'—'}</strong></td><td>${s?fmtFull(s.submittedAt):'—'}</td><td>${s?btn('Lihat','review-student',`data-id="${s.id}"`,'text','book'):'—'}</td></tr>`;}).join('')||'<tr><td colspan="6">Belum ada siswa di kelas ini.</td></tr>'}</tbody></table></div>`;}
function history(){const date=current().query.get('date')||SS.jakartaDay(),all=model.attendanceForActor().filter(a=>a.day===date),classId=current().query.get('class')||'',items=all.filter(a=>!classId||model.find('users',a.userId)?.classId===classId);return pageHead('REKAP KEHADIRAN','Hadir untuk tumbuh bersama.','Catatan hadir siswa dan guru. Tidak ada catatan belum tentu berarti tidak hadir.',linkBtn('Buka absensi','attendance','primary','check'))+`<form class="filter-bar" data-form="history-filter">${field('Tanggal (WIB)','date',date,'date','required')}${select('Kelas','class',accessibleClasses(),classId,false)}<button class="btn secondary" type="submit">Tampilkan</button>${btn('Ekspor CSV','export-attendance','','secondary','download')}</form><div class="table-wrap"><table><thead><tr><th>Nama</th><th>ID</th><th>Peran / kelas</th><th>Waktu hadir (WIB)</th><th>Status</th></tr></thead><tbody>${items.sort((a,b)=>b.time.localeCompare(a.time)).map(a=>`<tr><td><strong>${h(a.name)}</strong></td><td><code>${h(a.code)}</code></td><td>${SS.roles[a.role]}${a.className?' · '+h(a.className):''}</td><td>${fmtTime(a.time)}</td><td>${pill(a.status,'green')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty-table">Belum ada catatan kehadiran untuk filter ini.</td></tr>'}</tbody></table></div>`;}
function news(id){
  if(id){const n=model.find('news',id);if(!n)return empty('Berita tidak ditemukan','Berita mungkin telah dihapus oleh admin.');return `<a class="back-link" href="#/news">${ico('back',16)}Semua kabar sekolah</a>`+pageHead(h(n.category),h(n.title),fmtDate(n.createdAt))+`<article class="reading-panel">${n.imageId?`<img class="article-image" data-file-image="${h(n.imageId)}" alt="${h(n.title)}">`:''}<div class="prose">${h(n.content).replace(/\n/g,'<br>')}</div></article>`;}
  return pageHead('CERITA DARI SEKOLAH KITA','Kabar baik, semangat baru.','Berita sekolah, informasi penting, dan apresiasi untuk siswa berprestasi.')+`<div class="section-heading"><h2>Papan informasi</h2><span>${model.data.announcements.length} informasi</span></div><div class="notice-grid">${model.data.announcements.map(n=>`<article class="notice-card">${ico('news',23)}<small>${fmtDate(n.createdAt)}</small><h3>${h(n.title)}</h3><p>${h(n.content).replace(/\n/g,'<br>')}</p></article>`).join('')||empty('Belum ada informasi','Informasi dari admin sekolah akan tampil di sini.')}</div><div class="section-heading space-top"><h2>Berita sekolah</h2></div><div class="news-grid">${model.data.news.map(n=>`<article class="news-card">${n.imageId?`<img data-file-image="${h(n.imageId)}" alt="${h(n.title)}">`:`<div class="news-cover">${ico('news',40)}<span>KABAR SEKOLAH</span></div>`}<div><small>${h(n.category)} · ${fmtDate(n.createdAt)}</small><h3><a href="#/news/${n.id}">${h(n.title)}</a></h3><p>${h(n.content.slice(0,130))}…</p><a class="text-link" href="#/news/${n.id}">Baca cerita ${ico('arrow',17)}</a></div></article>`).join('')||empty('Belum ada berita','Cerita kegiatan sekolah akan tampil di sini.')}</div><div class="section-heading space-top"><h2>Siswa berprestasi</h2><span>Setiap usaha patut diapresiasi</span></div><div class="achievement-grid">${model.data.achievements.map(p=>`<article class="achievement-card">${p.imageId?`<img data-file-image="${h(p.imageId)}" alt="${h(p.name)}">`:`<span class="award-avatar">${ico('star',35)}</span>`}<small>${h(p.className||'Siswa sekolah')}</small><h3>${h(p.name)}</h3><strong>${h(p.title)}</strong><p>${h(p.description)}</p></article>`).join('')||empty('Belum ada publikasi prestasi','Apresiasi siswa dapat ditambahkan oleh admin.')}</div>`;
}
function admin(type='classes'){
  if(model.actor.role!=='admin')return accessDenied();if(!['classes','subjects','users','clubs'].includes(type))type='classes';
  const labels={classes:'Kelas',subjects:'Mata pelajaran',users:'Akun pengguna',clubs:'Ekstrakurikuler'};
  const items=model.data[type].filter(v=>normSearch(v));
  return pageHead('ADMINISTRASI SEKOLAH','Data sekolah','Kelola data utama dan penugasan pengguna dari satu tempat.',btn('Tambah '+labels[type].toLowerCase(),'edit-master',`data-type="${type}"`))+`<div class="tabs">${Object.entries(labels).map(([key,label])=>`<a href="#/admin/${key}" class="${key===type?'active':''}">${label}<span>${model.data[key].length}</span></a>`).join('')}</div><div class="search-bar"><label><span>Cari ${labels[type].toLowerCase()}</span><input id="master-search" type="search" value="${h(filter)}" placeholder="Ketik nama atau ID…"></label><span>${items.length} data</span></div><div id="master-table">${masterTable(type,items)}</div>`;
}
function normSearch(v){return SS.norm(JSON.stringify(v)).includes(SS.norm(filter));}
function masterTable(type,items){return `<div class="table-wrap"><table><thead><tr><th>${type==='users'?'Nama pengguna':'Nama'}</th><th>${type==='users'?'ID & peran':'Keterangan'}</th><th>${type==='users'?'Kelas / penugasan':type==='clubs'?'Pembina':'Jumlah terkait'}</th><th>Aksi</th></tr></thead><tbody>${items.map(v=>`<tr><td><strong>${h(v.name)}</strong></td><td>${type==='users'?`<code>${h(v.code)}</code><br>${pill(SS.roles[v.role])}`:type==='classes'?`Tingkat ${h(v.level)} · ${h(v.year)}`:type==='clubs'?h(v.schedule||'—'):'Mata pelajaran sekolah'}</td><td>${type==='users'?(v.role==='siswa'?'Kelas '+h(className(v.classId)):v.role==='guru'?h(v.classIds.map(className).join(', ')||'Belum ditugaskan')+'<br><small>'+h(v.subjectIds.map(subjectName).join(', '))+'</small>':v.role==='admin'?'Seluruh sekolah':h(model.data.clubs.filter(c=>c.coachIds.includes(v.id)).map(c=>c.name).join(', ')||'Belum ditugaskan')):type==='classes'?model.data.users.filter(u=>u.classId===v.id).length+' siswa':type==='clubs'?h(v.coachIds.map(userName).join(', ')):model.data.materials.filter(m=>m.subjectId===v.id).length+' materi'}</td><td><div class="row-actions"><button class="icon-btn" data-action="edit-master" data-type="${type}" data-id="${v.id}" aria-label="Edit ${h(v.name)}">${ico('edit',18)}</button><button class="icon-btn danger-icon" data-action="delete-master" data-type="${type}" data-id="${v.id}" aria-label="Hapus ${h(v.name)}">${ico('trash',18)}</button></div></td></tr>`).join('')||'<tr><td colspan="4" class="empty-table">Tidak ada data yang cocok.</td></tr>'}</tbody></table></div>`;}
function publications(type='news'){if(model.actor.role!=='admin')return accessDenied();if(!['news','announcements','achievements'].includes(type))type='news';const labels={news:'Berita sekolah',announcements:'Papan informasi',achievements:'Siswa berprestasi'};return pageHead('PUBLIKASI SEKOLAH','Bagikan cerita dan informasi.','Konten tersimpan pada browser ini dan ditampilkan di Kabar sekolah.',btn('Tambah publikasi','edit-publication',`data-type="${type}"`))+`<div class="tabs">${Object.entries(labels).map(([k,v])=>`<a href="#/publications/${k}" class="${k===type?'active':''}">${v}</a>`).join('')}</div><div class="panel">${model.data[type].map(n=>`<div class="list-row"><span class="row-icon">${ico(type==='achievements'?'star':'news')}</span><div><strong>${h(n.title)}</strong><small>${n.name?h(n.name)+' · ':''}${fmtDate(n.createdAt)}</small></div><div class="row-actions">${btn('Edit','edit-publication',`data-type="${type}" data-id="${n.id}"`,'text','edit')}<button class="icon-btn danger-icon" data-action="delete-publication" data-type="${type}" data-id="${n.id}" aria-label="Hapus ${h(n.title)}">${ico('trash',18)}</button></div></div>`).join('')||empty('Belum ada publikasi','Tambahkan konten pertama untuk sekolah Anda.')}</div>`;}
function accessDenied(){return empty('Halaman tidak tersedia','Data tidak ditemukan atau akun Anda tidak mempunyai akses ke halaman ini.',linkBtn('Kembali ke ringkasan','dashboard','secondary'));}
async function hydrateImages(){const elements=[...document.querySelectorAll('[data-file-image]')];for(const el of elements){try{const blob=await model.repo.getFile(el.dataset.fileImage);if(blob&&el.isConnected){const url=URL.createObjectURL(blob);objectUrls.push(url);el.src=url;}}catch{el.alt='Gambar tidak tersedia';}}}
function updateProgress(){const form=document.querySelector('[data-form="take-task"]');if(!form)return;const task=model.find('assignments',form.dataset.id),answers=Object.fromEntries(new FormData(form));const answered=task.questions.filter(q=>String(answers[q.id]||'').trim()).length;document.getElementById('answered-count').textContent=`${answered} dari ${task.questions.length} soal terjawab`;session.set('draft-'+model.actor.id+'-'+task.id,JSON.stringify(answers));}
function render(){
  objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];
  const {parts:[route,id]}=current();
  const publicRoutes=['login','attendance','news'];
  if(!model.actor&&!publicRoutes.includes(route)){loginRedirect=(location.hash.slice(2)||'dashboard');location.hash='/login';return;}
  let content,active=route;
  if(route==='login') {app.innerHTML=login();return;}
  if(route==='attendance'){app.innerHTML=attendance();return;}
  if(route==='dashboard')content=dashboard();
  else if(route==='learn')content=learning(id);
  else if(route==='clubs')content=clubs(id);
  else if(route==='material'){content=material(id);active=model.find('materials',id)?.clubId?'clubs':'learn';}
  else if(route==='task'){content=task(id);active='learn';}
  else if(route==='results'){content=results(id);active='learn';}
  else if(route==='history')content=history();
  else if(route==='admin')content=admin(id);
  else if(route==='publications')content=publications(id);
  else if(route==='news')content=news(id);
  else content=accessDenied();
  app.innerHTML=model.actor?shell(content,active):publicShell(content,'news');
  hydrateImages();updateProgress();
}
async function routeChange(){if(!model)return;await model.refresh();closeModal();render();window.scrollTo({top:0,behavior:'instant'});}

function masterEditor(type,id){
  model.requireAdmin();const v=id?model.find(type,id):{};if(!v)throw new Error('Data tidak ditemukan.');
  const names={classes:'kelas',subjects:'mata pelajaran',users:'akun pengguna',clubs:'ekstrakurikuler'};
  let fields=field(type==='users'?'Nama lengkap':'Nama','name',v.name||'','text','required maxlength="200"');
  if(type==='classes')fields+=`<div class="two-fields">${select('Tingkat','level',[1,2,3,4,5,6].map(n=>({id:String(n),name:'Kelas '+n})),v.level||'4')}${field('Tahun ajaran','year',v.year||'2026/2027','text','required pattern="[0-9]{4}/[0-9]{4}" placeholder="2026/2027"')}</div>`;
  if(type==='users'){
    fields+=`<div class="two-fields">${field('ID login','code',v.code||'','text','required pattern="[A-Za-z0-9_-]{3,30}" maxlength="30" placeholder="Misal: SISWA004"')}${select('Peran','role',Object.entries(SS.roles).map(([id,name])=>({id,name})),v.role||'siswa')}</div><div id="role-fields">${roleFields(v.role||'siswa',v)}</div><p class="field-hint">Penugasan guru ke ekstrakurikuler diatur lewat tab Ekstrakurikuler. ID saja belum menjadi pengamanan akun untuk operasional.</p>`;
  }
  if(type==='clubs')fields+=area('Deskripsi','description',v.description||'','required')+field('Jadwal (WIB)','schedule',v.schedule||'','text','placeholder="Jumat · 14.00–15.30 WIB"')+checks('Pembina kegiatan','coachIds',model.data.users.filter(u=>['guru','pembina'].includes(u.role)),v.coachIds||[]);
  modal(`${id?'Edit':'Tambah'} ${names[type]}`,`<form data-form="master" data-type="${type}" data-id="${id||''}">${fields}${formFooter()}</form>`);
}
function roleFields(role,v={}){return role==='siswa'?select('Kelas siswa','classId',model.data.classes,v.classId||'')+checks('Ekstrakurikuler yang diikuti','clubIds',model.data.clubs,v.clubIds||[]):role==='guru'?checks('Kelas yang diajar','classIds',model.data.classes,v.classIds||[])+checks('Mata pelajaran yang diajar','subjectIds',model.data.subjects,v.subjectIds||[]):`<div class="hint-box">${role==='admin'?'Admin dapat mengelola seluruh data dan publikasi sekolah.':'Penugasan pembina dipilih pada Data sekolah → Ekstrakurikuler.'}</div>`;}
function scopeFields(v,clubId=''){
  if(clubId)return `<input type="hidden" name="clubId" value="${h(clubId)}"><p class="hint-box">Materi untuk ${h(model.find('clubs',clubId)?.name)}</p>`;
  const u=model.actor,subjects=model.data.subjects.filter(s=>u.role==='admin'||u.subjectIds.includes(s.id));
  return `<div class="two-fields">${select('Kelas','classId',accessibleClasses(),v.classId||'')}${select('Mata pelajaran','subjectId',subjects,v.subjectId||'')}</div>`;
}
function materialEditor(id,classId,clubId){
  model.require('admin','guru','pembina');const v=id?model.find('materials',id):{classId,clubId};if(!v||(id&&!model.canEdit(v)))throw new Error('Materi tidak dapat diedit.');
  modal(id?'Edit materi':'Tambah materi',`<form data-form="material" data-id="${id||''}">${field('Judul materi','title',v.title||'','text','required maxlength="200"')}${scopeFields(v,v.clubId)}${area('Isi materi','content',v.content||'','placeholder="Tulis penjelasan, petunjuk, atau materi belajar…" rows="7"')}<label class="field"><span>${v.fileId?'Ganti lampiran (opsional)':'Lampiran (opsional)'}</span><input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt"><small>PDF, JPG, PNG, WebP, TXT · Maksimal 5 MB${v.fileName?' · Saat ini: '+h(v.fileName):''}</small></label>${v.fileId?'<label class="checkbox-row"><input name="removeFile" type="checkbox">Hapus lampiran lama</label>':''}<label class="checkbox-row permission-toggle"><input type="checkbox" name="downloadable" ${v.downloadable!==false?'checked':''}><span><strong>Izinkan materi diunduh</strong><small>Jika nonaktif, tombol unduh disembunyikan. Konten yang tampil tetap dapat disalin atau ditangkap layar.</small></span></label>${formFooter('Simpan materi')}</form>`);
}
function questionEditor(q,i){
  return `<section class="builder-question" data-index="${i}"><div class="question-number">PERTANYAAN ${i+1}<button class="icon-btn danger-icon" type="button" data-action="remove-question" data-index="${i}" aria-label="Hapus pertanyaan ${i+1}">${ico('trash',18)}</button></div>${area('Pertanyaan','qtext-'+i,q.text,'required maxlength="200" rows="2"')}<div class="two-fields">${select('Jenis soal','qtype-'+i,[{id:'choice',name:'Pilihan ganda'},{id:'boolean',name:'Benar / salah'},{id:'short',name:'Jawaban singkat'}],q.type)}${field('Bobot poin','qpoints-'+i,q.points,'number','required min="1" max="100" step="1"')}</div>${q.type==='choice'?`<div class="option-editor"><span>Pilihan & kunci jawaban</span>${q.options.map((option,j)=>`<label><input aria-label="Pilih kunci jawaban ${String.fromCharCode(65+j)}" type="radio" name="qanswer-${i}" value="${j}" ${q.answer===String(j)?'checked':''} required><span>${String.fromCharCode(65+j)}</span><input type="text" name="qoption-${i}-${j}" aria-label="Pilihan ${String.fromCharCode(65+j)}" value="${h(option)}" required maxlength="300" placeholder="Tulis pilihan jawaban"></label>`).join('')}<small>Klik bulatan di samping jawaban yang benar.</small></div>`:q.type==='boolean'?select('Kunci jawaban','qanswer-'+i,[{id:'0',name:'Benar'},{id:'1',name:'Salah'}],q.answer):field('Kunci jawaban singkat','qanswer-'+i,q.answer,'text','required placeholder="Contoh: 1/2|2/4"')}${q.type==='short'?'<p class="field-hint">Pisahkan alternatif dengan |. Huruf besar/kecil dan spasi berlebih diabaikan; ejaan lainnya harus sama.</p>':''}</section>`;
}
function gatherBuilder(){const form=dialog.querySelector('form');if(!form)return;const fd=new FormData(form);builder=builder.map((q,i)=>({...q,text:String(fd.get('qtext-'+i)||''),points:Number(fd.get('qpoints-'+i)||1),answer:String(fd.get('qanswer-'+i)??''),options:q.type==='choice'?q.options.map((_,j)=>String(fd.get('qoption-'+i+'-'+j)||'')):q.options}));}
function drawQuestions(){document.getElementById('builder-questions').innerHTML=builder.map(questionEditor).join('');document.getElementById('question-count').textContent=`${builder.length} soal`;}
function taskEditor(id,classId){
  model.require('admin','guru');const v=id?model.find('assignments',id):{classId,questions:[]};if(!v||(id&&!model.canEdit(v)))throw new Error('Tugas tidak dapat diedit.');
  if(id&&model.data.submissions.some(s=>s.assignmentId===id))throw new Error('Tugas sudah memiliki jawaban siswa. Buat tugas baru agar nilai lama tetap utuh.');
  builder=JSON.parse(JSON.stringify(v.questions.length?v.questions:[{id:SS.uid(),text:'',type:'choice',options:['','','',''],answer:'',points:10}]));
  const due=v.dueAt?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v.dueAt)).replace(' ','T'):'';
  modal(id?'Edit tugas':'Buat tugas & kunci jawaban',`<form data-form="task-editor" data-id="${id||''}">${field('Judul tugas','title',v.title||'','text','required maxlength="200"')}${area('Petunjuk pengerjaan','description',v.description||'')}${scopeFields(v)}${field('Batas pengumpulan (WIB, opsional)','dueAt',due,'datetime-local')}<p class="field-hint">Siswa mendapat satu kesempatan. Nilai = bobot benar ÷ bobot total × 100.</p><div class="builder-heading"><h3>Pertanyaan</h3><span id="question-count">${builder.length} soal</span></div><div id="builder-questions">${builder.map(questionEditor).join('')}</div>${btn('Tambah pertanyaan','add-question','','secondary','plus')}${formFooter('Terbitkan tugas')}</form>`,'wide');
}
function publicationEditor(type,id){model.requireAdmin();const v=id?model.find(type,id):{};if(!v)throw new Error('Publikasi tidak ditemukan.');let fields=field(type==='achievements'?'Nama prestasi / penghargaan':'Judul','title',v.title||'','text','required maxlength="200"');if(type==='achievements')fields+=`<div class="two-fields">${field('Nama siswa','name',v.name||'','text','required')}${field('Kelas siswa','className',v.className||'')}</div>`+area('Keterangan prestasi','description',v.description||'');else fields+=(type==='news'?field('Kategori','category',v.category||'Kegiatan sekolah'):'')+area(type==='news'?'Isi berita':'Isi informasi','content',v.content||'','required rows="7"');if(type!=='announcements')fields+=`<label class="field"><span>Foto ${v.imageId?'pengganti ':''}(opsional)</span><input type="file" name="image" accept=".jpg,.jpeg,.png,.webp"><small>JPG, PNG, WebP · Maksimal 5 MB. Gunakan foto yang berhak dipublikasikan.</small></label>${v.imageId?'<label class="checkbox-row"><input name="removeImage" type="checkbox">Hapus foto lama</label>':''}`;modal((id?'Edit ':'Tambah ')+({news:'berita',announcements:'informasi',achievements:'prestasi'}[type]),`<form data-form="publication" data-type="${type}" data-id="${id||''}">${fields}${formFooter('Simpan publikasi')}</form>`);}
function confirmAction(title,body,action,data=''){modal(title,`<p class="confirm-copy">${body}</p>${errorBox}<div class="form-actions"><button type="button" class="btn secondary" data-action="close-dialog">Batal</button><button type="button" class="btn danger" data-action="${action}" ${data}>Ya, lanjutkan</button></div>`,'narrow');}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function csv(rows){return '\ufeff'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');}
async function viewAttachment(id){const m=model.find('materials',id);if(!m||!model.canRead(m))throw new Error('Akses materi tidak tersedia.');const file=await model.repo.getFile(m.fileId);if(!file)throw new Error('Lampiran tidak ditemukan pada browser ini.');const url=URL.createObjectURL(file);objectUrls.push(url);let view;if(file.type.startsWith('image/'))view=`<img class="file-preview-image" src="${url}" alt="${h(m.title)}">`;else if(file.type==='text/plain')view=`<pre class="text-preview">${h(await file.text())}</pre>`;else view=`<iframe class="pdf-preview" title="${h(m.title)}" src="${url}${m.downloadable?'':'#toolbar=0&navpanes=0'}"></iframe><p class="field-hint">Jika browser ponsel tidak menampilkan PDF, gunakan browser desktop.${m.downloadable?' Anda juga dapat mengunduh lampiran.':''}</p>`;modal(h(m.fileName||m.title),view+(m.downloadable?`<div class="form-actions">${btn('Unduh lampiran','download-material',`data-id="${id}"`,'primary','download')}</div>`:''),'wide');}
async function handleAction(el){
  const a=el.dataset.action,d=el.dataset;
  if(a==='close-dialog'){closeModal();return;}
  if(a==='trial-info'){modal('Tentang trial Smart Santri',`<div class="prose"><p>Versi ini berjalan di GitHub Pages tanpa server. Semua akun dan data awal adalah contoh.</p><ul><li>Data dan lampiran disimpan di IndexedDB browser ini. Browser atau perangkat lain memiliki data terpisah.</li><li>Menghapus data situs juga menghapus data trial. Mode privat dapat menghapus data saat ditutup.</li><li>Login hanya memakai ID agar peran mudah dicoba. Pembatasan peran di sisi browser belum melindungi data dari manipulasi.</li><li>Jawaban benar dan nilai trial masih berada di browser. Operasional memerlukan autentikasi, otorisasi, database, penyimpanan berkas, dan penilaian di server.</li><li>“Tidak dapat diunduh” berarti tombol unduh dinonaktifkan, bukan perlindungan antisalinkan.</li></ul><p><strong>Gunakan data contoh, bukan data siswa sungguhan.</strong></p></div>`);return;}
  if(a==='demo-id'){document.querySelector('[name="code"]').value=d.code;document.querySelector('[name="code"]').focus();return;}
  if(a==='logout'){model.actorId='';session.remove('smart-santri-user');location.hash='/login';render();return;}
  if(a==='toggle-sidebar'){const side=document.getElementById('sidebar');side.classList.toggle('open');el.setAttribute('aria-expanded',String(side.classList.contains('open')));return;}
  if(a==='edit-master'){masterEditor(d.type,d.id);return;}
  if(a==='delete-master'){confirmAction('Hapus data sekolah?','Data yang masih terhubung dengan akun, materi, atau riwayat tidak dapat dihapus.','confirm-delete-master',`data-type="${d.type}" data-id="${d.id}"`);return;}
  if(a==='confirm-delete-master'){await model.deleteMaster(d.type,d.id);closeModal();render();toast('Data berhasil dihapus.');return;}
  if(a==='edit-material'){materialEditor(d.id,d.class,d.club);return;}
  if(a==='delete-material'){confirmAction('Hapus materi?','Materi akan dihapus dari ruang belajar.','confirm-delete-material',`data-id="${d.id}"`);return;}
  if(a==='confirm-delete-material'){const m=model.find('materials',d.id),route=m.clubId?'clubs/'+m.clubId:'learn/'+m.classId;await model.deleteMaterial(d.id);closeModal();location.hash='/'+route;toast('Materi berhasil dihapus.');return;}
  if(a==='view-file'){await viewAttachment(d.id);return;}
  if(a==='download-material'){const m=model.find('materials',d.id);if(!m||!model.canRead(m)||!m.downloadable)throw new Error('Unduh tidak diizinkan untuk materi ini.');const file=m.fileId?await model.repo.getFile(m.fileId):new Blob([m.title+'\n\n'+m.content],{type:'text/plain;charset=utf-8'});if(!file)throw new Error('Lampiran tidak tersedia.');download(file,m.fileName||m.title.replace(/[^\p{L}\p{N}\s_-]/gu,'').slice(0,80)+'.txt');return;}
  if(a==='edit-task'){taskEditor(d.id,d.class);return;}
  if(a==='add-question'){gatherBuilder();if(builder.length>=50)throw new Error('Maksimal 50 pertanyaan per tugas.');builder.push({id:SS.uid(),text:'',type:'choice',options:['','','',''],answer:'',points:10});drawQuestions();document.querySelector('.builder-question:last-child').scrollIntoView({block:'nearest'});return;}
  if(a==='remove-question'){if(builder.length===1)throw new Error('Sisakan minimal satu pertanyaan.');gatherBuilder();builder.splice(Number(d.index),1);drawQuestions();return;}
  if(a==='delete-task'){confirmAction('Hapus tugas?','Tugas yang sudah memiliki nilai siswa tidak dapat dihapus.','confirm-delete-task',`data-id="${d.id}"`);return;}
  if(a==='confirm-delete-task'){const t=model.find('assignments',d.id);await model.deleteAssignment(d.id);closeModal();location.hash='/learn/'+t.classId;toast('Tugas berhasil dihapus.');return;}
  if(a==='confirm-submit'){if(!pendingSubmission)throw new Error('Jawaban tidak tersedia. Muat kembali tugas.');const s=await model.submit(pendingSubmission.id,pendingSubmission.answers);session.remove('draft-'+model.actor.id+'-'+pendingSubmission.id);pendingSubmission=null;closeModal();render();toast('Jawaban terkirim. Nilai kamu: '+s.score);return;}
  if(a==='review-student'){const s=model.find('submissions',d.id),t=s&&model.find('assignments',s.assignmentId);if(!s||!t||model.actor.role==='siswa'||!model.canRead(t))throw new Error('Nilai tidak dapat diakses.');modal('Jawaban '+h(userName(s.studentId)),resultView(t,s),'wide');return;}
  if(a==='export-scores'){const t=model.find('assignments',d.id);if(!t||!model.canRead(t)||model.actor.role==='siswa')throw new Error('Anda tidak memiliki akses ke nilai ini.');const rows=[['ID','Nama','Kelas','Tugas','Nilai','Bobot benar','Bobot total','Dikumpulkan (WIB)'],...model.data.users.filter(u=>u.role==='siswa'&&u.classId===t.classId).map(u=>{const s=model.data.submissions.find(s=>s.assignmentId===t.id&&s.studentId===u.id);return[u.code,u.name,className(u.classId),t.title,s?.score??'',s?.earned??'',s?.possible??'',s?fmtFull(s.submittedAt):'Belum mengumpulkan'];})];download(new Blob([csv(rows)],{type:'text/csv;charset=utf-8'}),'nilai-smart-santri.csv');return;}
  if(a==='export-attendance'){const date=current().query.get('date')||SS.jakartaDay(),classId=current().query.get('class')||'';const rows=[['Tanggal','ID','Nama','Peran','Kelas','Waktu (WIB)','Status'],...model.attendanceForActor().filter(a=>a.day===date&&(!classId||model.find('users',a.userId)?.classId===classId)).map(a=>[a.day,a.code,a.name,SS.roles[a.role],a.className,fmtTime(a.time),a.status])];download(new Blob([csv(rows)],{type:'text/csv;charset=utf-8'}),'absensi-'+date+'.csv');return;}
  if(a==='edit-publication'){publicationEditor(d.type,d.id);return;}
  if(a==='delete-publication'){confirmAction('Hapus publikasi?','Publikasi tidak akan ditampilkan lagi di Kabar sekolah.','confirm-delete-publication',`data-type="${d.type}" data-id="${d.id}"`);return;}
  if(a==='confirm-delete-publication'){await model.deletePublication(d.type,d.id);closeModal();render();toast('Publikasi berhasil dihapus.');return;}
}
document.addEventListener('click',async event=>{if(event.target.closest('.skip')){event.preventDefault();document.getElementById('main-content')?.focus();return;}const el=event.target.closest('[data-action]');if(!el)return;event.preventDefault();if(el.disabled)return;el.disabled=true;try{await handleAction(el);}catch(err){if(dialog.open)showError(dialog,err);else toast(err.message,true);}finally{el.disabled=false;}});
document.addEventListener('change',event=>{
  if(event.target.name==='role'&&event.target.closest('[data-form="master"]')){const form=event.target.form;const existing=model.find('users',form.dataset.id)||{};document.getElementById('role-fields').innerHTML=roleFields(event.target.value,existing);}
  if(event.target.name?.startsWith('qtype-')){gatherBuilder();const i=Number(event.target.name.split('-')[1]),q=builder[i];q.type=event.target.value;q.answer='';q.options=q.type==='choice'?['','','','']:q.type==='boolean'?['Benar','Salah']:[];drawQuestions();}
  if(event.target.closest('[data-form="take-task"]'))updateProgress();
});
document.addEventListener('input',event=>{if(event.target.id==='master-search'){filter=event.target.value;const type=current().parts[1]||'classes';document.getElementById('master-table').innerHTML=masterTable(type,model.data[type].filter(normSearch));}if(event.target.closest('[data-form="take-task"]'))updateProgress();});
document.addEventListener('submit',async event=>{
  const form=event.target.closest('[data-form]');if(!form)return;event.preventDefault();const button=form.querySelector('[type="submit"]');if(button?.disabled)return;if(button)button.disabled=true;
  const fd=new FormData(form),data=Object.fromEntries(fd),type=form.dataset.form;let newFile='';
  try{
    if(type==='login'){const u=model.login(data.code);session.set('smart-santri-user',u.id);const target=loginRedirect;loginRedirect='dashboard';location.hash='/'+target;render();return;}
    if(type==='attendance'){const r=await model.attend(data.code);form.reset();attendancePopup(r);return;}
    if(type==='master'){['classIds','subjectIds','clubIds','coachIds'].forEach(key=>data[key]=fd.getAll(key));await model.saveMaster(form.dataset.type,{...data,id:form.dataset.id});closeModal();render();toast('Data sekolah berhasil disimpan.');return;}
    if(type==='material'){
      const old=form.dataset.id?model.find('materials',form.dataset.id):null;let fileId=data.removeFile?'':old?.fileId||'',fileName=data.removeFile?'':old?.fileName||'',fileType=data.removeFile?'':old?.fileType||'';
      const file=fd.get('attachment');if(file?.size){const info=await model.upload(file);newFile=info.id;fileId=info.id;fileName=info.name;fileType=info.type;}
      await model.saveMaterial({...data,id:form.dataset.id,fileId,fileName,fileType,downloadable:fd.has('downloadable')});newFile='';closeModal();render();toast('Materi berhasil disimpan.');return;
    }
    if(type==='task-editor'){gatherBuilder();const dueAt=data.dueAt?new Date(data.dueAt+':00+07:00').toISOString():'';await model.saveAssignment({...data,id:form.dataset.id,questions:builder,dueAt});closeModal();render();toast('Tugas dan kunci jawaban berhasil diterbitkan.');return;}
    if(type==='take-task'){pendingSubmission={id:form.dataset.id,answers:data};const t=model.find('assignments',form.dataset.id);if(!t.questions.every(q=>String(data[q.id]||'').trim()))throw new Error('Jawab semua pertanyaan sebelum mengirim.');modal('Kirim jawaban sekarang?',`<p class="confirm-copy">Semua ${t.questions.length} pertanyaan sudah dijawab. Setelah dikirim, jawaban tidak dapat diubah dan nilai langsung ditampilkan.</p>${errorBox}<div class="form-actions"><button type="button" class="btn secondary" data-action="close-dialog">Periksa lagi</button><button type="button" class="btn primary" data-action="confirm-submit">Kirim jawaban ${ico('check',18)}</button></div>`,'narrow');return;}
    if(type==='history-filter'){location.hash='/history?'+new URLSearchParams({date:data.date,class:data.class});render();return;}
    if(type==='publication'){const old=form.dataset.id?model.find(form.dataset.type,form.dataset.id):null;let imageId=data.removeImage?'':old?.imageId||'';const file=fd.get('image');if(file?.size){const info=await model.upload(file,true);newFile=info.id;imageId=info.id;}await model.savePublication(form.dataset.type,{...data,id:form.dataset.id,imageId});newFile='';closeModal();render();toast('Publikasi berhasil disimpan.');return;}
  }catch(err){if(newFile)await model.repo.deleteFile(newFile).catch(()=>{});showError(form,err);}finally{if(button)button.disabled=false;}
});
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeModal();}});
window.addEventListener('hashchange',()=>routeChange().catch(err=>toast(err.message,true)));
document.addEventListener('keydown',event=>{if(event.key==='Escape'){document.getElementById('sidebar')?.classList.remove('open');document.querySelector('.mobile-menu')?.setAttribute('aria-expanded','false');}});
setInterval(()=>{const time=document.getElementById('live-clock');if(time){time.textContent=fmtTime(new Date());document.getElementById('live-date').textContent=fmtDate(new Date());}},1000);
window.addEventListener('focus',()=>{if(model&&!dialog.open&&!document.querySelector('form'))model.refresh().then(render).catch(err=>toast(err.message,true));});
(async()=>{try{model=await new SS.Model(await new SS.BrowserRepository().open()).open();const id=session.get('smart-santri-user');if(id&&model.find('users',id))model.actorId=id;if(!location.hash)location.hash=model.actor?'/dashboard':'/login';else render();}catch(err){app.innerHTML=publicShell(empty('Penyimpanan tidak tersedia',h(err.message)),'');}})();
